### ISSUE TITLE
Add user api resource to get/update profile info

### ISSUE THREAD

**Issue by beaorn** [CropQuest/reports-api#14]
Need api resource to get the user's own profile information, as well as update their own:

- email
- first_name
- last_name
- city
- region
- country

**Comment by miguejs** [comment]
Let me  work on this

**Comment by beaorn** [comment]
@miguejs sounds good, let me know if you need more info

**Comment by miguejs** [comment]
@beaorn  How can  I put my credentials in the api request header?

**Comment by beaorn** [comment]
@miguejs the app is setup w/ doorkeeper so you will need to add new app at http://localhost:3000/oauth/applications as logged in admin user which will give you client id and secret to use, make sure to set redirect uri for local use urn:ietf:wg:oauth:2.0:oob. 

Its set up to use authorization code grant flow, so you can use an API client like [postman](https://www.getpostman.com/) with those credentials and redirect uri and the following endpoints:

- authorize_url: http://localhost:3000/oauth/authorize
- token_url: http://localhost:3000/oauth/token

This will give you access and refresh tokens and the API controller [gets the resource owner id (user) from doorkeeper token](https://github.com/CropQuest/reports-api/blob/master/app/controllers/api/api_controller.rb#L20) so you can call current_resource_owner in the new user API controller to get their info.
